package com.februy.shop.dao.pay;

import com.februy.shop.common.domain.entity.pay.Balance;
import org.apache.ibatis.annotations.Mapper;

/**
 * @Author: fnbory
 * @Date: 21/12/2019 下午 7:36
 */
@Mapper
public interface BalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated
     */
    int insert(Balance record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated
     */
    Balance selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table balance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Balance record);
}