package com.februy.shop.dao.user;

import com.februy.shop.common.domain.entity.user.User;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Author: fnbory
 * @Date: 20/12/2019 下午 8:21
 */
@Mapper
public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);



    User findByUsername(@Param("username") String username);
    List<User> findIdAndNameByUsernameContaining(@Param("username") String username);
    User findByPhone(@Param("phone") String phone);
    Page<User> findAll(@Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
    String findAvatarById(@Param("id") Long id);
    User findBriefInfoById(@Param("id") Long id);
    List<Long> findAllUserIds();
    User findByEmail(@Param("email") String email);
}
