package com.februy.shop.common.domain.entity.product;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.februy.shop.common.enumeration.product.ProductType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.io.Serializable;

/**
 * @Author: fnbory
 * @Date: 22/12/2019 下午 4:59
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Product implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbggenerated
     */
    @NotNull
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated
     */
    @NotNull
    @Min(1)
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated
     */
    @NotNull
    private ProductCategory category;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbggenerated
     */
    @NotNull
    private ProductType type;
    @NotNull
    private String description;
    @JsonIgnore
    private Boolean isOnPromotion;
    private String imageUrl;
}
