package com.februy.shop.dao.order;

import com.februy.shop.common.domain.dto.order.OrderQueryConditionDTO;
import com.februy.shop.common.domain.entity.order.Order;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * @Author: fnbory
 * @Date: 23/12/2019 下午 9:14
 */
@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int insert(Order record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);



    Page<Order> findAll(@Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
    Page<Order> findByCondition(@Param("condition") OrderQueryConditionDTO condition, @Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
}