package com.februy.shop.common.domain.entity.pay;

import com.februy.shop.common.domain.entity.user.User;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

/**
 * @Author: fnbory
 * @Date: 21/12/2019 下午 7:30
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Balance implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.user
     *
     * @mbggenerated
     */
    private User user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.balance
     *
     * @mbggenerated
     */
    private Double balance;
    private String paymentPassword;
}