package com.februy.shop.common.domain.entity.order;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.februy.shop.common.domain.entity.product.Product;
import com.februy.shop.common.domain.entity.user.User;
import com.februy.shop.common.enumeration.order.OrderStatus;
import com.februy.shop.common.properties.DateTimeProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @Author: fnbory
 * @Date: 23/12/2019 下午 8:59
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Order implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product
     *
     * @mbggenerated
     */
    @NotNull
    private Product product;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.quantity
     *
     * @mbggenerated
     */
    @NotNull
    @Min(1)
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user
     *
     * @mbggenerated
     */
    @NotNull
    private User user;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.place_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = DateTimeProperties.LOCAL_DATE_TIME_PATTERN)
    private LocalDateTime placeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.total_price
     *
     * @mbggenerated
     */
    @NotNull
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated
     */
    private OrderStatus orderStatus;

}
