spring:
  redis:
  # Redis数据库索引（默认为0）
    database: 0  
  # 连接池最大连接数（使用负值表示没有限制）
    pool.max-active: 8  
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    pool.max-wait: 5000 
  # 连接池中的最大空闲连接
    pool.max-idle: 8  
  # 连接池中的最小空闲连接
    pool.min-idle: 0  
  # 连接超时时间（毫秒）
    timeout: 0
    #    cluster:
    nodes:
      - 47.100.213.16:6379

  rocketmq:
    consumer:
      namesrv-addr: 47.100.213.16:9876
      group-name: account-consumer
      topic: account
      check-keys: check
      consume-failure-retry-times: 3
    producer:
      namesrv-addr: 47.100.213.16:9876
      group-name: account-transaction-message-producer
      topic: account-check


  datasource:
    url: jdbc:mysql://47.100.213.16:3306/shop_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 10
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQueryTimeout: 900000
    validationQuery: SELECT SYSDATE() from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
