package com.februy.shop.common.domain.entity.message;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.februy.shop.common.enumeration.message.MessageStatus;
import com.februy.shop.common.properties.DateTimeProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @Author: fnbory
 * @Date: 24/12/2019 下午 1:58
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ProducerTransactionMessage implements Serializable {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.msgId
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.message_status
     *
     * @mbggenerated
     */
    private MessageStatus messageStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = DateTimeProperties.LOCAL_DATE_TIME_PATTERN)
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = DateTimeProperties.LOCAL_DATE_TIME_PATTERN)
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.send_times
     *
     * @mbggenerated
     */
    private Integer sendTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column producer_transaction_message.body
     *
     * @mbggenerated
     */
    private byte[] body;
}
