package com.februy.shop.dao.product;

import com.februy.shop.common.domain.entity.product.Product;
import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * @Author: fnbory
 * @Date: 22/12/2019 下午 5:36
 */
@Mapper
public interface ProductMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    Page<Product> findByCategoryPaging(@Param("categoryId") Long category, @Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);

    List<Product> findByCategory(@Param("categoryId") Long category);

    List<Product> findOnPromotion();

    List<Product> findSimpleByCategory(@Param("categoryId") Long category);

    List<Long> findProductIdsByCategory(@Param("categoryId")Long category);
}
